### ISSUE TITLE
Dynamicly resize mycanvas with Javascript

### ISSUE THREAD

**Issue by minguotan** [KaliedaRik/Scrawl-canvas#40]
Hello, as a beginner of scrawl-canvas, I wonder if it's possible to resize mycanvas according to the size of img which is dynamicly changing.
I tried to cover a canvas on an img, always fitting in the img size, and then I can make notes on different imgs. The problem is, once imported scrawl module and set that canvas tag as "data-scrawl-canvas", there seems an initial setting for that with {width:0;height:0;display:block;} in inline styles, which makes it hard to override by further javascripts.
Besides, each time when the makeRender() calls, such initial setting will guarantee above settings  being reset again, which means if I want to do something with scrawl, I have to abandon the idea of dynamicly resizing mycanvas with Javascript.
Am I use it a wrong way? Thanks!
Here is the basic Html to show the relation of "note" canvas and the dynamicly-changing "background" img
`<div class="img_wrapper" >
        <img src="" alt="" >
        <canvas
                id="mycanvas"
                data-scrawl-canvas
        ></canvas>
    </div>`

**Comment by KaliedaRik** [comment]
Hi, Minguotan. From the code snippet you included at the end of your comment I'm assuming that you want both the image and the canvas to dynamically resize to fit the img_wrapper div container yes? What I don't know is whether you want the image to appear directly above the canvas, or you want to use the image as an asset which can be drawn in the canvas.

SC canvases can be dynamically resized to match a div container's size. They can also use responsive img elements as assets. Much of this should be automated for you without having to worry about writing additional Javascript. See Test demo Canvas-025 for a range of examples of how to do this (the code can be found by clicking in the link near the bottom of the demo page - https://scrawl-v8.rikweb.org.uk/demo/canvas-025.html

**Comment by minguotan** [comment]
> 

Thank you very much, it's more elegant to view img as an asset of canvas.
I tried by using a dynamically changing image as an asset, but it never works well, the canvas show nothing. Can you help to have a look at it? Many thanks:)
Here is the raw Html
` <div class="img_wrapper" >
        <img src="" alt="" class="canvasImg removedEle">
        <canvas
                id="mycanvas"
                data-scrawl-canvas
                data-is-responsive="true"
                data-fit="cover"
        ></canvas>
    </div>`
Here is the function to resize the image asset:
`function reSize(img,w,h){
//resize canvas
let mycanvas = $("#mycanvas");
        myCanvas.attr("data-base-width",w);
        myCanvas.attr("data-base-height",h);
        myCanvas.width=w;
        myCanvas.height=h;
//resize img
        $(img).attr("srcset",src+" "+w+"w");
        $(img).attr("data-dimensions","["+w+","+h+"]");
        canvasImg();}`
and here is the canvasImg() module:
`export function canvasImg(){
    const canvas = L.artefact.mycanvas;
    importDomImage('.canvasImg');
    makePicture({
        name: `${canvas.name}-image`,
        group: canvas.base.name,
        asset: "river",
        width: "100%",
        height: "100%",
        copyWidth: "100%",
        copyHeight: "100%"
    });
    const namespace = "demo2";
    const name = (n) => `${namespace}-${n}`;
    makeRender({
        name: name('img'),
        target: canvas,
    });
}`

**Comment by KaliedaRik** [comment]
Don't resize the canvas wrapper directly - `myCanvas.h = h` won't work. If you want to set the attributes of any SC object, you need to use its `.set()` function.

Have you been through any of the lessons on the website?

- Lesson 1 covers the getting started basics - https://scrawl-v8.rikweb.org.uk/learn/first-lesson/
- Lesson 2 covers importing and using images - https://scrawl-v8.rikweb.org.uk/learn/second-lesson/

**Comment by minguotan** [comment]
> Don't resize the canvas wrapper directly - `myCanvas.h = h` won't work. If you want to set the attributes of any SC object, you need to use its `.set()` function.
> 
> Have you been through any of the lessons on the website?
> 
> * Lesson 1 covers the getting started basics - https://scrawl-v8.rikweb.org.uk/learn/first-lesson/
> * Lesson 2 covers importing and using images - https://scrawl-v8.rikweb.org.uk/learn/second-lesson/

My apology, I did finish the first three lessons which I thought I may start to do some tests and I'm sorry for not familiar with basic concepts of SC.
The result for now is, dynamically image importing is just a basic step which should not take up too much calculations for each switch to rerender. So I have to get back to use both <img> and <canvas> rather than copy or import img to canvas. 
To do that, the default setting of canvas "display:block" have to be overrided in other way, where the set() function won't work. I'll find if there are other way in lessons to achieve that.
Rreally appreciate your help here. Thanks!
