### ISSUE TITLE
anchors of pictures are in the default nav

### ISSUE THREAD

**Issue by riw** [KaliedaRik/Scrawl-canvas#68]
hi
thanks for your work on this library! i'm not sure if i'm missing something or if i've found a bug:
when i put a block with an anchor on my canvas, the anchor tag is added to the canvas nav.
when I put an image with an anchor on my canvas, the anchor tag is added to the default nav.
is this a bug or the intended behavior? how could i get the anchor tag of the image in the canvas nav?

**Comment by KaliedaRik** [comment]
Hi @riw - thanks for raising this issue!

I've just addressed the behaviour (which was a bug) at the weekend in PR https://github.com/KaliedaRik/Scrawl-canvas/pull/67, which has now merged into the v8-dev branch. I have a little more work to do around tabbing order for anchors and the new Button object (see PR https://github.com/KaliedaRik/Scrawl-canvas/pull/69) after which I'm planning to do a new release, hopefully this coming weekend.

**Comment by KaliedaRik** [comment]
This is now fixed in release v8.12.0
